# Generated by Django 5.2.1 on 2025-06-19 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botblock',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='botblock',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='botblock',
            name='next_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bots.botblock'),
        ),
        migrations.AlterField(
            model_name='botblock',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
