# Generated by Django 5.2.1 on 2025-06-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botblock',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='botblock',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
