# Generated by Django 5.2.1 on 2025-06-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_alter_botblock_options_botblock_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botblock',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='botblock',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
