# Generated by Django 5.2.1 on 2025-06-18 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_alter_botblock_options_botblock_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botblock',
            options={'ordering': ['position'], 'verbose_name': 'Блок', 'verbose_name_plural': 'Блоки'},
        ),
        migrations.AddField(
            model_name='botblock',
            name='x',
            field=models.PositiveIntegerField(default=0, verbose_name='Позиция X'),
        ),
        migrations.AddField(
            model_name='botblock',
            name='y',
            field=models.PositiveIntegerField(default=0, verbose_name='Позиция Y'),
        ),
        migrations.AlterField(
            model_name='botblock',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='botblock',
            name='next_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_blocks', to='bots.botblock', verbose_name='Следующий блок'),
        ),
        migrations.AlterField(
            model_name='botblock',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='botblock',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок блока'),
        ),
    ]
