# Generated by Django 5.2.1 on 2025-06-20 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_blocktransition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botblock',
            name='next_block',
        ),
        migrations.AddField(
            model_name='botblock',
            name='block_type',
            field=models.CharField(choices=[('message', 'Сообщение'), ('input', 'Ввод'), ('button', 'Кнопки'), ('api', 'API-запрос')], default='message', max_length=20),
        ),
        migrations.CreateModel(
            name='BlockButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='bots.botblock')),
                ('to_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bots.botblock')),
            ],
        ),
        migrations.DeleteModel(
            name='BlockTransition',
        ),
    ]
